#!/bin/bash

# Author: Takunda Nhau
# Date Created: 05/01/2026
# Last Modified: 05/01/2026

# Description:
# Creates a  backup in ~/Documents/scripts/backup folder for all files in the home directory

# Usage:
# backup_script

tar -cvf ~/Documents/scripts/bash_scripts_"$(date +%d-%m-%Y_%H-%M-%S)".tar ~/* 2>/dev/null
exit 0
